blank_issues_enabled: false
contact_links:
  - name: Subway Builder Discord
    url: https://discord.gg/jrNQpbytUQ
    about: Get help or discuss mods and maps
  - name: Documentation
    url: https://subwaybuildermodded.com/
    about: Read the unofficial modding documentation
