import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import YAML from "yaml";
import Ajv, { type ErrorObject } from "ajv";
import addFormats from "ajv-formats";
import {
  DEFAULT_MAP_DATA_SOURCE,
  LEVEL_OF_DETAIL_VALUES,
  LOCATION_TAGS,
  SOURCE_QUALITY_VALUES,
  SPECIAL_DEMAND_TAGS,
} from "./lib/map-constants.js";

const REPO_ROOT = resolve(import.meta.dirname, "..");
const TEMPLATE_DIR = resolve(REPO_ROOT, ".github", "ISSUE_TEMPLATE");
const PUBLISH_TEMPLATE_PATH = resolve(TEMPLATE_DIR, "publish-map.yml");
const UPDATE_TEMPLATE_PATH = resolve(TEMPLATE_DIR, "update-map.yml");
const GENERATED_HEADER =
  "# AUTO-GENERATED by scripts/generate-map-templates.ts. Do not edit directly.";

const YAML_OPTIONS = {
  lineWidth: 92,
  indent: 2,
  defaultStringType: "QUOTE_DOUBLE",
  blockQuote: true,
} as const;

const ajv = new Ajv({ allErrors: true, strict: false });
addFormats(ajv);

const ISSUE_FORM_SCHEMA = {
  type: "object",
  required: ["name", "description", "title", "labels", "body"],
  properties: {
    name: { type: "string", minLength: 1 },
    description: { type: "string", minLength: 1 },
    title: { type: "string", minLength: 1 },
    labels: {
      type: "array",
      items: { type: "string", minLength: 1 },
      minItems: 1,
    },
    body: {
      type: "array",
      minItems: 1,
      items: { $ref: "#/$defs/bodyItem" },
    },
  },
  $defs: {
    optionItem: {
      anyOf: [
        { type: "string", minLength: 1 },
        {
          type: "object",
          required: ["label"],
          properties: {
            label: { type: "string", minLength: 1 },
            required: { type: "boolean" },
          },
          additionalProperties: true,
        },
      ],
    },
    bodyItem: {
      type: "object",
      required: ["type", "attributes"],
      properties: {
        type: {
          type: "string",
          enum: ["markdown", "input", "textarea", "checkboxes", "dropdown"],
        },
        id: { type: "string", minLength: 1 },
        attributes: { type: "object" },
        validations: {
          type: "object",
          properties: {
            required: { type: "boolean" },
          },
          additionalProperties: true,
        },
      },
      additionalProperties: true,
      allOf: [
        {
          if: { properties: { type: { const: "markdown" } } },
          then: {
            properties: {
              attributes: {
                type: "object",
                required: ["value"],
                properties: {
                  value: { type: "string", minLength: 1 },
                },
                additionalProperties: true,
              },
            },
          },
          else: {
            required: ["id"],
            properties: {
              attributes: {
                type: "object",
                required: ["label"],
                properties: {
                  label: { type: "string", minLength: 1 },
                  description: { type: "string", minLength: 1 },
                  placeholder: { type: "string" },
                  render: { type: "string" },
                  value: { type: "string" },
                  options: {
                    type: "array",
                    items: { $ref: "#/$defs/optionItem" },
                  },
                },
                additionalProperties: true,
              },
            },
          },
        },
      ],
    },
  },
};

const validateIssueForm = ajv.compile(ISSUE_FORM_SCHEMA);

type TemplateValue = Record<string, unknown>;
type TemplateField = {
  type: string;
  id: string;
  attributes: Record<string, unknown>;
  validations?: { required: boolean };
};
type FieldOptions = {
  placeholder?: string;
  value?: string;
  render?: string;
  required?: boolean;
};
type CheckboxOption = string | { label: string; required?: boolean };

function markdown(value: string): TemplateValue {
  return {
    type: "markdown",
    attributes: { value },
  };
}

function spacer(): TemplateValue {
  return markdown("<br>");
}

function input(
  id: string,
  label: string,
  description: string,
  opts: FieldOptions = {},
): TemplateValue {
  const item: TemplateField = {
    type: "input",
    id,
    attributes: { label, description },
  };
  if (opts.placeholder !== undefined)
    item.attributes.placeholder = opts.placeholder;
  if (opts.value !== undefined) item.attributes.value = opts.value;
  if (opts.required !== undefined)
    item.validations = { required: opts.required };
  return item;
}

function textarea(
  id: string,
  label: string,
  description: string,
  opts: FieldOptions = {},
): TemplateValue {
  const item: TemplateField = {
    type: "textarea",
    id,
    attributes: { label, description },
  };
  if (opts.render !== undefined) item.attributes.render = opts.render;
  if (opts.placeholder !== undefined)
    item.attributes.placeholder = opts.placeholder;
  if (opts.required !== undefined)
    item.validations = { required: opts.required };
  return item;
}

function checkboxes(
  id: string,
  label: string,
  description: string,
  options: readonly CheckboxOption[],
): TemplateValue {
  return {
    type: "checkboxes",
    id,
    attributes: {
      label,
      description,
      options: options.map((entry) =>
        typeof entry === "string" ? { label: entry } : entry,
      ),
    },
  };
}

function dropdown(
  id: string,
  label: string,
  description: string,
  options: readonly string[],
  required: boolean,
): TemplateValue {
  return {
    type: "dropdown",
    id,
    attributes: {
      label,
      description,
      options,
    },
    validations: {
      required,
    },
  };
}

function mapIdField(description: string): TemplateValue {
  return input("map-id", "Map ID", description, {
    placeholder: "raleigh",
    required: true,
  });
}

const SHARED_FIELDS_AFTER_MAP_ID = [
  // ===== Data Validation ===== //
  input(
    "name",
    "City Name",
    "The human-readable city name shown in Railyard. This is the title of the map that people will see when downloading it.",
    { placeholder: "Raleigh", required: true },
  ),
  input(
    "city-code",
    "City Code",
    "2-4 letter IATA/ICAO-style city code used by the game internally. Must be uppercase letters/numbers. Must not clash with vanilla city codes or other registered maps. Check existing maps before choosing a code.",
    { placeholder: "RDU", required: true },
  ),
  input(
    "country",
    "Country Code",
    "ISO 3166-1 alpha-2 country code - two uppercase letters (e.g. US, GB, CA, DE, JP). Used to group maps by country in Railyard. It is REQUIRED that you use ISO codes according to this list: https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes.",
    { placeholder: "US", required: true },
  ),
  input(
    "population",
    "Population",
    "Approximate metropolitan area population. Number only, no commas or separators. Used for display and sorting in Railyard and does not need to be exact.",
    { placeholder: "1500000", required: true },
  ),
  textarea(
    "description",
    "Description",
    "A short description of what your map offers. Markdown is supported. This is shown in the map browser. Mention data quality, notable features, or coverage area.",
    {
      render: "markdown",
      placeholder:
        "Custom map of the Raleigh-Durham metropolitan area with good demand data quality.",
      required: true,
    },
  ),
  spacer(),
  // ===== Data Validation ===== //
  markdown(
    "## Data Attestation\n\nProvide details about your map's data source, data source quality, and level of detail. Be honest and transparent in your descriptions and please include the methodology you used to generate the map's data.",
  ),
  input(
    "data_source",
    "Data Source",
    "Enter the data source used to generate the demand data for your map. The source name should use common abbreviations like LODES/INSEE/ONS etc.",
    { placeholder: "LODES, etc.", value: DEFAULT_MAP_DATA_SOURCE, required: false },
  ),
  dropdown(
    "source_quality",
    "Source Quality",
    "Approximate quality of the data source used for your map. Official gov't sources are considered high-quality while raw open-source data is considered low-quality. If your data source includes OSM, we will not consider that high-quality data.",
    SOURCE_QUALITY_VALUES,
    true,
  ),
  dropdown(
    "level_of_detail",
    "Level of Detail",
    "Approximate level of detail of your map. Demand resolution at the level of census blocks is considered high-detail, while neighborhood/city resolutions are considered low-detail.",
    LEVEL_OF_DETAIL_VALUES,
    true,
  ),
  input(
    "methodology",
    "Methodology",
    "Description of how demand data was generated for your map. Please include any details about overcoming data source limitations or any augmentations done with real-world data.",
    { placeholder: "Transcribed raw OSM data", required: true },
  ),
  spacer(),
  // ===== Map Tagging / Images  ===== //
  markdown(
    "## Tagging & Image Preview\n\nRailyard allows users to search for maps based on tags and presents a preview image for discovery. Please check whichever tags best represent your map. Note that `Location` is required.",
  ),
  dropdown(
    "location",
    "Location",
    "Select all tags that apply to your map. These help users find your map in the browser.",
    LOCATION_TAGS,
    true,
  ),
  spacer(),
  markdown(
    "### Special Demand Tag Guide\n\nUse these tags only when the map models a meaningful amount of demand related to the feature.\n\n- `airports`: passenger (non-worker) demand from major airports\n- `entertainment`: leisure/tourist demand at stadiums/venues/nightlife\n- `ferries`: passenger (non-worker) demand from ferry terminals\n- `hospitals`: visitation demand for major medical centers\n- `parks`: leisure/tourist demand from large local or national parks\n- `schools`: demand from primary/secondary school students\n- `universities`: demand from university school students",
  ),
  checkboxes(
    "special_demand",
    "Special Demand",
    "Select all tags that apply to your map. These help users find your map in the browser.",
    SPECIAL_DEMAND_TAGS,
  ),
  textarea(
    "gallery",
    "Gallery Images",
    "Drag and drop screenshots here, or paste image URLs (one per line). These will be displayed in the map browser. At least one image is required.",
    { required: true },
  ),
  spacer(),
  // ===== Source Code Validation ===== //
  markdown(
    "## Source Code Information\n\nProvide information on where your map is hosted so that Railyard will be able to check your repository for updates and allow users to install the map on demand.",
  ),
  input(
    "source",
    "Source URL",
    "URL to your map's source code repository or download page.",
    { placeholder: "https://github.com/username/sb-raleigh", required: true },
  ),
  dropdown(
    "update-type",
    "Update Type",
    "The method used by Railyard to fetch updates for your map. Most maps should use GitHub Releases. Use Custom URL only if you host your own update.json file.",
    ["GitHub Releases", "Custom URL"],
    true,
  ),
  input(
    "github-repo",
    "GitHub Repository",
    "Required ONLY if you selected GitHub Releases. The `owner/repo` path (e.g. `username/sb-raleigh`). The repo must exist, have at least one release, and the latest release must contain a .zip asset. Leave blank if using Custom URL.",
    { placeholder: "username/sb-raleigh" },
  ),
  input(
    "custom-update-url",
    "Custom Update URL",
    "Required ONLY if you selected Custom URL. The full URL to your self-hosted update.json file. The file must follow the Railyard update.json schema. Leave blank if using GitHub Releases.",
    { placeholder: "https://example.com/sb-raleigh/update.json" },
  ),
  spacer(),
  // ===== Authorization ===== //
  markdown(
    "## Authorization.",
  ),
  {
    type: "checkboxes",
    id: "terms",
    attributes: {
      label: "Terms",
      options: [
        {
          label:
            "I attest that I am the author or this map or have been granted permission by the author to publish this map to Railyard.",
          required: true,
        },
      ],
    },
  },
];

const publishTemplateDoc = {
  name: "Publish New Map",
  description: "Submit a new custom map to The Railyard registry.",
  title: "[Publish Map]: ",
  labels: ["publish-map"],
  body: [
    markdown(
      "# Publish a New Map\n\nFill out the form below to submit your custom map to The Railyard. A pull request will be automatically created for review.\n\nIf validation fails, you can edit this issue and comment **revalidate** to retry.",
    ),
    spacer(),
    markdown(
      "## Identifiers\n\nProvide details about the city/metropolitan area your map models. These data will be used to import your map into the game and to give Railyard users context abour your map",
    ),
    mapIdField(
      "A unique identifier for your map in kebab-case. This is the permanent directory name in the registry and cannot be changed later. Must be unique across all maps - if another map of the same city already exists, use a distinct ID (e.g. `london-detailed`, `london-mini`). Only lowercase letters, numbers, and hyphens allowed.",
    ),
    ...SHARED_FIELDS_AFTER_MAP_ID,
  ],
};

const updateTemplateDoc = {
  name: "Update Existing Map Metadata",
  description: "Update metadata for a map you own in The Railyard registry.",
  title: "[Update Map]: ",
  labels: ["update-map"],
  body: [
    markdown(
      "# Update Map Metadata\n\nOnly fill in the fields you want to change - leave everything else blank.\nYour GitHub account must match the original publisher of this map.\n\nIf validation fails, you can edit this issue and comment **revalidate** to retry.",
    ),
    spacer(),
    markdown(
      "## Identifiers\n\nProvide details about the city/metropolitan area your map models. These data will be used to import your map into the game and to give Railyard users context abour your map",
    ),
    mapIdField(
      "The ID of the map you want to update. Must already exist in the registry.",
    ),
    ...SHARED_FIELDS_AFTER_MAP_ID,
  ],
};

function normalizeNewlines(content: string): string {
  return content.replace(/\r\n/g, "\n");
}

function buildTemplateFile(doc: TemplateValue): string {
  return `${GENERATED_HEADER}\n${YAML.stringify(doc, YAML_OPTIONS)}`;
}

function failValidation(
  label: string,
  errors: readonly ErrorObject[] | null | undefined,
): never {
  const details = (errors || [])
    .map(
      (err) =>
        `${err.instancePath || "/"} ${err.message || ""}`.trim(),
    )
    .join("\n");
  throw new Error(
    `Schema validation failed for ${label}${details ? `:\n${details}` : "."}`,
  );
}

function validateTemplateDoc(label: string, doc: TemplateValue): void {
  const valid = validateIssueForm(doc);
  if (!valid) {
    failValidation(label, validateIssueForm.errors);
  }
}

function parseTemplateFile(path: string): TemplateValue {
  const raw = normalizeNewlines(readFileSync(path, "utf-8"));
  const parsed = YAML.parse(raw) as unknown;
  if (!parsed || typeof parsed !== "object") {
    throw new Error(`Failed to parse YAML object from ${path}`);
  }
  return parsed as TemplateValue;
}

function getFieldId(item: unknown): string | undefined {
  if (!item || typeof item !== "object") return undefined;
  const candidate = item as { id?: unknown };
  return typeof candidate.id === "string" ? candidate.id : undefined;
}

function verifySharedTail() {
  const publishMapIdIndex = publishTemplateDoc.body.findIndex(
    (item) => getFieldId(item) === "map-id",
  );
  const updateMapIdIndex = updateTemplateDoc.body.findIndex(
    (item) => getFieldId(item) === "map-id",
  );

  if (publishMapIdIndex === -1 || updateMapIdIndex === -1) {
    throw new Error("Template bodies must include a `map-id` field.");
  }

  const publishTail = JSON.stringify(publishTemplateDoc.body.slice(publishMapIdIndex + 1));
  const updateTail = JSON.stringify(updateTemplateDoc.body.slice(updateMapIdIndex + 1));
  if (publishTail !== updateTail) {
    throw new Error("Template bodies after map-id must remain identical.");
  }
}

function stableStringify(value: unknown): string {
  return JSON.stringify(value);
}

function main(): void {
  verifySharedTail();
  validateTemplateDoc("publish-map (generated)", publishTemplateDoc);
  validateTemplateDoc("update-map (generated)", updateTemplateDoc);

  const publishContent = buildTemplateFile(publishTemplateDoc);
  const updateContent = buildTemplateFile(updateTemplateDoc);
  const isCheckMode = process.argv.includes("--check");

  if (!isCheckMode) {
    writeFileSync(PUBLISH_TEMPLATE_PATH, publishContent);
    writeFileSync(UPDATE_TEMPLATE_PATH, updateContent);
    console.log("Generated publish-map.yml and update-map.yml");
    return;
  }

  const publishActual = parseTemplateFile(PUBLISH_TEMPLATE_PATH);
  const updateActual = parseTemplateFile(UPDATE_TEMPLATE_PATH);
  validateTemplateDoc("publish-map (checked)", publishActual);
  validateTemplateDoc("update-map (checked)", updateActual);

  const publishMatches =
    stableStringify(publishActual) === stableStringify(publishTemplateDoc);
  const updateMatches =
    stableStringify(updateActual) === stableStringify(updateTemplateDoc);

  if (!publishMatches || !updateMatches) {
    console.error("Map issue templates are out of date.");
    console.error("Run: pnpm --dir scripts run generate-map-templates");
    process.exit(1);
  }
  console.log("Map issue templates are in sync.");
}

main();
